name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [17]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '${{ matrix.java }}'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_AUTH }}
          project_id: discord-api-406418

      - name: Access secrets from Google Secret Manager
        uses: google-github-actions/secrets-manager@main
        with:
          project: discord-api-406418
          secrets: Discord_TOKEN
        id: secrets

      - name: Deploy to GCP
        run: |
          gcloud app deploy --service-account=discord-api-406418@appspot.gserviceaccount.com
